In [7]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
print(tf.__version__)    #2.4.1

def pp():
    return print("####################################")

2.4.1


In [ ]:
#physical_devices = tf.config.list_physical_devices("GPU")
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#print (x_train[5])
print(len(x_train[5]))
pp()
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0     #将二维数组转化成一维数组
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0
print(x_train.shape)  #(60000, 784)
print(x_train[5])   #输出第五个element
print(x_train[5].shape)  #输出第一个element的维度  (784,)


In [22]:
(train_image, train_labels),_ = tf.keras.datasets.mnist.load_data()
print (train_labels[5])
print (len(train_labels))
# 对图片进行预处理
train_image = tf.expand_dims(train_image,-1) # 扩增维度
#print(train_image.shape)  #(60000, 28, 28, 1)
#print(train_image[0])    #输出第一个element
pp()


# 计算梯度必须使用浮点型
# 归一化
train_image = tf.cast(train_image/255, tf.float32)
print(train_image.shape)  #(60000, 28, 28, 1)
#print(train_image[0])    #输出第一个element
print(train_image[0].shape)    #输出第一个element的维度   (28, 28, 1)

pp()

# 对label进行处理
train_labels = tf.cast(train_labels, tf.int64)

print(train_labels.shape)  #(60000,)
print(train_labels[0])    #输出第一个element  tf.Tensor(5, shape=(), dtype=int64)
print(train_labels[0].shape)    #输出第一个element的维度 ()

2
60000
####################################
(60000, 28, 28, 1)
(28, 28, 1)
####################################
(60000,)
tf.Tensor(5, shape=(), dtype=int64)
()


In [ ]:
import tensorflow as tf
(train_image, train_labels),_ = tf.keras.datasets.mnist.load_data()

# 对图片进行预处理
train_image = tf.expand_dims(train_image,-1) # 扩增维度

# 计算梯度必须使用浮点型
# 归一化
train_image = tf.cast(train_image/255, tf.float32)

# 对label进行处理
train_labels = tf.cast(train_labels, tf.int64)

dataset = tf.data.Dataset.from_tensor_slices((train_image, train_labels))

# 连续、批次
dataset = dataset.shuffle(10000).batch(32)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,[3,3],activation="relu",input_shape=(None,None,1)),
    tf.keras.layers.Conv2D(32,[3,3],activation="relu"),
    tf.keras.layers.GlobalMaxPool2D(),
    tf.keras.layers.Dense(10)
])

optimizer = tf.keras.optimizers.Adam()   # 优化器，默认Adam参数

loss_func = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

train_loss = tf.keras.metrics.Mean("train_loss")
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy('train_accuracy')

def train_step(model,images,labels):
    with tf.GradientTape() as t:
        pred = model(images)
        loss_step = loss_func(labels,pred)
    grads = t.gradient(loss_step, model.trainable_variables)
    optimizer.apply_gradients(zip(grads,model.trainable_variables))
    train_loss(loss_step)
    train_accuracy(labels,pred)

def train():
    for epoch in range(10):     # 训练10个epoch
        for (batch,(images,labels)) in enumerate(dataset):
            train_step(model,images,labels)
        print("Epoch{} loss is {},accuracy is {}".format(epoch,
                                                         train_loss.result(),
                                                         train_accuracy.result()))
        # 对于下一步进行重置
        train_loss.reset_states()
        train_accuracy.reset_states()

train()        

In [ ]:
import os
import sys

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist


def pp():
    return print("####################################") 
#physical_devices = tf.config.list_physical_devices("GPU")
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# x_train里面每一个element都是二维数组
print (x_train[45])
print(len(x_train[45]))
pp()
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0

print(x_train.shape)  #(60000, 28, 28, 1)
#print(x_train[0])    #输出第一个element
pp()
print(x_train[45])    #输出第一个element
print(x_train[45].shape)    #输出第一个element的维度

In [24]:
name = "Alice"
age = 25

print(f"Hello, {name}! You are {age} years old.")

Hello, Alice! You are 25 years old.


In [26]:


# 假设我们有一个二分类的数据集，其中 X 是输入，y 是标签
Q = np.array([[1.1, 0.6], [-2.8, 2.4]])
y = np.array([1.87,1.09])
Z = y*Q
print (Z)




[[ 2.057  0.654]
 [-5.236  2.616]]


In [35]:
import numpy as np

# 创建一个 1x2 的矩阵
matrix1 = np.array([[2, 3],[4,5],[3,5]])

# 创建一个 2x2 的矩阵
matrix2 = np.array([[1,2,3], [4,5,6]])

print (matrix1)
print (matrix2)


# 计算两个矩阵的和
result = matrix1 * matrix2

# 打印结果
print(result)

[[2 3]
 [4 5]
 [3 5]]
[[1 2 3]
 [4 5 6]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [46]:
import numpy as np

# 创建一个 1x2 的矩阵
matrix1 = np.array([1, 2])

# 创建一个 2x2 的矩阵
matrix2 = np.array([[3, 4], [5, 6]])

print (matrix1)
print (matrix2)
# 计算两个矩阵的和
result = matrix1 * matrix2

# 打印结果
print(result)

[1 2]
[[3 4]
 [5 6]]
[[ 3  8]
 [ 5 12]]


In [59]:
import numpy as np
def softmax(x):
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = [round(i/sum_exp_x,2) for i in exp_x]
    return y

a0=[0.1,0.2,0.3]
print(softmax(a0))
a1=[1,2,3]
print(softmax(a1))
a2=[10,20,30]
print(softmax(a2))
a3=[100,200,300]
print(softmax(a3))
a4=[100,200,]
print(softmax(a4))





[0.3, 0.33, 0.37]
[0.09, 0.24, 0.67]
[0.0, 0.0, 1.0]
[0.0, 0.0, 1.0]
[0.0, 1.0]
